//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int DealID { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<int> NeedID { get; set; }
    
        public virtual Needs Needs { get; set; }
        public virtual Offers Offers { get; set; }
    }
}
