//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyRE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agencyEDBEntities : DbContext
    {
        public agencyEDBEntities()
            : base("name=agencyEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Needs> Needs { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<RealEstates> RealEstates { get; set; }
        public virtual DbSet<Realtors> Realtors { get; set; }
        public virtual DbSet<TypeREs> TypeREs { get; set; }
    }
}
