//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Needs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Needs()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int NeedID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> RealtorID { get; set; }
        public Nullable<int> TypeREID { get; set; }
        public string AddressRE { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public string MinSquare { get; set; }
        public string MaxSquare { get; set; }
        public Nullable<int> MinRooms { get; set; }
        public Nullable<int> MaxRooms { get; set; }
        public Nullable<int> MinFlat { get; set; }
        public Nullable<int> MaxFlat { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual Realtors Realtors { get; set; }
        public virtual TypeREs TypeREs { get; set; }
    }
}
