//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offers()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int OfferID { get; set; }
        public int ClientID { get; set; }
        public int RealtorID { get; set; }
        public int RealEstatesID { get; set; }
        public decimal Price { get; set; }
        public string StatusDeal { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual RealEstates RealEstates { get; set; }
        public virtual Realtors Realtors { get; set; }
    }
}
