//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstates()
        {
            this.Offers = new HashSet<Offers>();
        }
    
        public int REID { get; set; }
        public int Vcode { get; set; }
        public string AddressRE { get; set; }
        public int TypeRE { get; set; }
        public string coordinates { get; set; }
        public Nullable<int> QuaRooms { get; set; }
        public Nullable<int> QuaFlats { get; set; }
        public Nullable<int> Flat { get; set; }
        public string Squares { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual TypeREs TypeREs { get; set; }
    }
}
